services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: syafana-app
    container_name: syafana-app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: syafana-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: syafana_profile
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:  
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network: 
    driver: bridge
